name: Create and Star 30 Repositories

on:
  schedule:
    - cron: "45 */4 * * *"
  workflow_dispatch:

jobs:
  create-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Create and Star Repositories
        run: |
          USER=$(gh api user --jq .login)

          for i in {1..30}
          do
          REPO="repo-$i"

           gh repo clone "$USER/$REPO"
           cd "$REPO"

            BRANCH="auto-update-$(date +%s)"
            git checkout -b "$BRANCH"

            # Always create real change
            echo "Update: $(date)" >> activity.log
            echo "Random: $RANDOM" >> activity.log

           git add activity.log
           git commit -m "Automated update"
           git push origin "$BRANCH"

           PR_URL=$(gh pr create \
          --title "Automated update" \
          --body "Routine update")

          PR_NUM=$(echo "$PR_URL" | grep -oE '[0-9]+$')

          gh pr merge "$PR_NUM" --squash --auto

          cd ..
          rm -rf "$REPO"
  done
    
