name: Create and Star 30 Repositories

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours
  workflow_dispatch:

jobs:
  create-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Create and Star Repositories
        run: |
          USER=$(gh api user --jq .login)

          for i in {1..30}
          do
            REPO="auto-repo-$RANDOM-$i"

            echo "Creating repository $REPO"
            gh repo create "$USER/$REPO" --public -y

            echo "Starring repository $REPO"
            gh api -X PUT user/starred/$USER/$REPO
          done
